# Generated by Django 4.0.6 on 2022-07-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='new', max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='type',
            name='name',
            field=models.CharField(default='task', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='issueTracker.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='issueTracker.type', verbose_name='type'),
        ),
    ]
