# Generated by Django 4.0.6 on 2022-07-15 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0002_alter_issue_status_alter_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(choices=[('task', 'task'), ('bug', 'bug'), ('enhancement', 'enhancement')], on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='issueTracker.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(choices=[('new', 'new'), ('in_progress', 'in progress'), ('done', 'done')], on_delete=django.db.models.deletion.PROTECT, related_name='types', to='issueTracker.type', verbose_name='type'),
        ),
    ]
