# Generated by Django 4.0.6 on 2022-07-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0002_remove_status_status_remove_type_type_status_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='type_old',
        ),
    ]
