# Generated by Django 4.0.6 on 2022-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0004_alter_issue_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(related_name='types', to='issueTracker.type'),
        ),
    ]
