# Generated by Django 4.0.6 on 2022-07-18 18:17

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Issue = apps.get_model('issueTracker', 'Issue')
    for issue in Issue.objects.all():
        issue.type.add(issue.type_old)


def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('issueTracker', 'Issue')
    for issue in Issue.objects.all():
        issue.type_old.set(issue.type.all())


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0005_issue_type'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
