# Generated by Django 4.0.6 on 2022-07-15 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0006_alter_issue_status_alter_issue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(limit_choices_to={'done': 'done', 'in_progress': 'in progress', 'new': 'new'}, on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='issueTracker.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(limit_choices_to={'bug': 'bug', 'enhancement': 'enhancement', 'task': 'task'}, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='issueTracker.type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=50, verbose_name='type'),
        ),
    ]
