# Generated by Django 4.0.6 on 2022-07-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0006_auto_20220718_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type_old',
        ),
    ]
