# Generated by Django 4.0.6 on 2022-07-26 02:33

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0007_remove_issue_type_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, default='', verbose_name='End date')),
                ('project_name', models.CharField(max_length=50, verbose_name='Project name')),
                ('project_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Project description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
    ]
