# Generated by Django 4.0.6 on 2022-07-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0009_alter_issue_status_alter_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=50, verbose_name='type'),
        ),
    ]
