# Generated by Django 4.0.6 on 2022-07-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0010_alter_status_status_alter_type_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
    ]
