# Generated by Django 4.0.6 on 2022-08-19 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name=django.core.validators.URLValidator()),
        ),
    ]
